### PR TITLE
Support built image to boot with secure boot enabled.

### PR DESCRIPTION
**Pull request by Anduin2017**
Support built image to boot with secure boot enabled.

Idea based on [https://gitlab.aiursoft.cn/anduin/anduinos/-/merge_requests/8/diffs](https://gitlab.aiursoft.cn/anduin/anduinos/-/merge_requests/8/diffs)

image

### CODE REVIEW

**Review by mvallim — APPROVED** [review]

**Comment by mvallim** [comment]
LGTM! :fire:

**Comment by Anduin2017** [comment]
I ran the latest commit build, and seems secure boot failed. Please do double confirm.

**Comment by Anduin2017** [comment]
Any help needed?

**Comment by Anduin2017** [comment]
Oh I noticed #65. Good luck!

**Comment by mvallim** [comment]
> Oh I noticed #65. Good luck!

Merged #65

**Pull request merged**
